name: Node.js CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd src/crawler && npm install
    - run: cd src/crawler && npm run lint
    - run: cd src/crawler && npm test
    - run: cd src/server && npm install && npm run build --if-present
      env:
        CI: true
